#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
    deb-systemd-invoke enable mqtt-service-control.service >/dev/null
	deb-systemd-invoke start mqtt-service-control.service >/dev/null
fi